[workspace]
resolver = "2"
members = ["cli", "crates/eth-trie-proofs", "crates/sn-trie-proofs"]

[workspace.dependencies]
eth-trie-proofs = { path = "crates/eth-trie-proofs" }
sn-trie-proofs = { path = "crates/sn-trie-proofs" }

alloy-primitives = { version = "1.4", features = ["serde"] }
alloy = { version = "1.0", features = [
    "rpc",
    "rpc-types",
    "rpc-client",
    "network",
    "providers",
    "eips",
    "transports",
    "transport-http",
    "consensus",
    "k256",
] }
alloy-rlp = { version = "0.3" }
clap = { version = "4.5", features = ["derive"] }
eth_trie = "0.6"
ethereum-types = "0.15"
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
serde_with = { version = "3.15.0", features = ["hex"] }
sn-merkle-trie = { git = "https://github.com/HerodotusDev/sn-merkle-trie.git", rev = "2d6aecfa4f29778ebc18c6bd0e6e5e9ee65a0a82" }
starknet-types-core = { version = "0.3", features = ["hash"] }
starknet-types-rpc = "0.7"
thiserror = "2.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.5.7"
