[package]
name = "sn-trie-proofs"
version = "0.2.0"
edition = "2021"
description = "Starknet Transaction Trie Proofs"
readme = "README.md"
keywords = ["mpt", "trie", "starknet"]
categories = ["cryptography", "data-structures"]
exclude = [".github"]

[dependencies]
reqwest.workspace = true
serde_json.workspace = true
sn-merkle-trie.workspace = true
starknet-types-core.workspace = true
starknet-types-rpc.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
