[package]
name = "eth-trie-proofs"
version = "0.2.0"
edition = "2021"
description = "Ethereum Transaction Trie Proofs"
readme = "README.md"
keywords = ["mpt", "trie", "ethereum"]
categories = ["cryptography", "data-structures"]
exclude = [".github"]

[dependencies]
alloy-rlp.workspace = true
alloy.workspace = true
eth_trie.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
dotenvy.workspace = true
tokio.workspace = true