[package]
name = "eth-trie-proofs"
version = "0.1.2"
edition = "2021"
description = "Ethereum Transaction Trie Proofs"
readme = "README.md"
license-file = "../../LICENSE"
repository = "https://github.com/HerodotusDev/eth-trie-proofs"
keywords = ["mpt", "trie", "ethereum"]
categories = ["cryptography", "data-structures"]
exclude = [".github"]

[dependencies]
alloy-rlp.workspace = true
alloy.workspace = true
eth_trie.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
tokio.workspace = true