name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run clippy for native
        run: cargo clippy --all --all-targets -- -D warnings

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run tests
        env:
            RPC_URL_ETHEREUM_MAINNET: ${{ secrets.RPC_URL_ETHEREUM_MAINNET }}
            RPC_URL_STARKNET_GATEWAY: ${{ secrets.RPC_URL_STARKNET_GATEWAY }}
            RPC_URL_STARKNET_TESTNET: ${{ secrets.RPC_URL_STARKNET_TESTNET }}
        run: cargo test --all --all-targets -- --nocapture
